Create landing page and add Google Sign Option
nmittu/STEP-CAPSTONE pull request #3
Opened 2020-06-18 15:43 UTC by Maryam676

- Created the initial landing page for user
- One sign in option for now 
- Appengine and firebase dependencies added to pom file
- Firebase app manager class for ensuring app is only created once

2020-06-18 16:09 UTC, nmittu requested changes

2020-06-18 16:09 UTC, nmittu commented on src/main/java/com/google/sps/servlets/SessionInit.java
> +public class SessionInit extends HttpServlet {
Why is this servlet empty?

2020-06-18 16:09 UTC, nmittu commented on src/main/java/com/google/sps/servlets/VerifySession.java
> +  static String getCookie(HttpServletRequest request, String name, String defaultValue) {
Move this to a helper class. Something like `RequestUtils`. This method can also be made `public`.

2020-06-18 16:09 UTC, nmittu commented on src/main/java/com/google/sps/servlets/VerifySession.java
> +public class VerifySession extends HttpServlet {
Try not to merge in incomplete servlets.

2020-06-18 17:04 UTC, nmittu requested changes

2020-06-18 17:04 UTC, nmittu commented on src/main/java/com/google/sps/servlets/SessionInit.java
> +import com.google.appengine.api.datastore.*;
Using a wildcard in imports can cause issues if the package contains a Class that interferes with other classes your using.  

https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad

2020-06-18 17:54 UTC, nmittu approved these changes

2020-06-18 17:58 UTC, biancasap approved these changes

2020-06-19 15:12 UTC, mdchu commented on src/main/java/com/google/sps/servlets/VerifySession.java
> +
stray line edit in otherwise unchanged file?

2020-06-19 15:12 UTC, mdchu approved these changes

2020-06-19 15:27 UTC, merged